pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                echo 'Building...'
            }
        }
    }
    post {
        success {
            // Trigger next job
            build job: 'pipeline-B'
        }
    }
}
